### ISSUE TITLE
"data" key missing from schema.json

### ISSUE THREAD

**Issue by nyobe** [dminkovsky/babel-relay-maven-plugin#1]
Hi there,

By default the babel-relay-plugin is configured to expect a top level 'data' key in the schema.json, because it is usually generated by saving the response of an endpoint (which are required to have this top level field by the spec). 

What do you think about either directly serializing the execution result, or to avoid the 'errors' key, adding the result data to a map with a single 'data' key and serializing that?

Thanks!

**Comment by dminkovsky** [comment]
Makes sense. Thank you.

**Comment by dminkovsky** [comment]
By the way—how did you find this library? How are you using it (installing to local repo?) (are you using it?)

**Comment by nyobe** [comment]
I found it via your comment on graphql-java/graphql-java#132 and using it via an artifactory repo - I think it will be very helpful for keeping our schema dump in sync!

**Comment by dminkovsky** [comment]
Great to hear! Thank you :)
чт, 22 дек. 2016 г. в 15:52, nyobe <notifications@github.com>:
